name: Deploy Next.js App to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/fair.pem
          chmod 600 ~/.ssh/fair.pem

      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          NEXT_PUBLIC_STAGE: ${{ secrets.NEXT_PUBLIC_STAGE }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/fair.pem $EC2_USER@$EC2_HOST << EOF
            echo " Removing old containers and images..."

            # Stop & remove old container (if exists)
            docker stop my-nextjs-app || true
            docker rm my-nextjs-app || true
            docker rmi my-nextjs-app || true

            docker stop nextjs-container || true
            docker rm nextjs-container || true

            echo " Building new Docker image..."
            docker build -t nextjs-app --build-arg NEXT_PUBLIC_STAGE=$NEXT_PUBLIC_STAGE .

            echo " Running container..."
            docker run -d --name nextjs-container -p 3000:3000 nextjs-app

            echo "🧼 Cleaning up Docker..."
            docker system prune -af --volumes
          EOF
