name: Deploy Next.js App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy on EC2
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Build and Run Docker on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            cd /home/ubuntu/AI-Lease-FE

            # Clean up old containers/images/volumes
            docker system prune -af --volumes

            # Build Docker image
            docker build -t nextjs-app --build-arg NEXT_PUBLIC_STAGE=${{ secrets.NEXT_PUBLIC_STAGE }} .

            # Stop and remove old container if running
            docker rm -f nextjs-container || true

            # Run new container
            docker run -d --name nextjs-container -p 3000:3000 nextjs-app
EOF
